site_name: AIOGQLC
site_description: "Python aynchronous/IO GraphQL client with file upload and subscription support."
site_url: https://doctorjohn.github.io/aiogqlc/
repo_url: https://github.com/DoctorJohn/aiogqlc/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - Operations:
      - Queries: queries.md
      - Mutations: mutations.md
      - File Uploads: file-uploads.md
      - Subscriptions: subscriptions.md
      - Authentication: authentication.md
      - Advanced Usage: advanced-usage.md
  - Guides:
      - Contributing: contributing.md
      - Migrating: migrating.md
